name: Deploy HTML to Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Clone another repository (optional)
        run: |
        # git clone https://github.com/your-username/your-repo.git

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ec2.pem
          chmod 600 ec2.pem
        # ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: clone repo
        run: |
          git clone https://github.com/chigo393/home-Deco.git

      - name: Move files to Apache directory and restart HTTP
        run: |
          ssh -0 StrictHostKeyChecking=no -i ec2.pem ${{ secrets.USERNAME }}@s{{ secrets.HOST }} << 'EOF'
          sudo cp -r /home/ec2-user@${{ secrets.SERVER_HOST }}/home-Deco* :/var/www/html/
          sudo systemctl enable httpd
          sudo systemctl restart httpd
          EOF
