name: Deploy HTML/CSS to Amazon Linux

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Install Apache and mod_ssl
        run: |
          sudo yum install -y httpd mod_ssl

      - name: Deploy to EC2
        run: |
        # sudo scp -i ~/.ssh/id_rsa index.html style.css ec2-user@ec2-18-135-99-102.eu-west-2.compute.amazonaws.com:/var/www/html/

      - name: Upload files using rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" index.html style.css ec2-user@${{ secrets.SERVER_HOST }}:/home/ec2-user/

      - name: Move files to /var/www/html with sudo
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.SERVER_HOST }} "sudo mv /home/ec2-user/index.html /var/www/html/"
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.SERVER_HOST }} "sudo mv /home/ec2-user/style.css /var/www/html/"
          
      - name: enable and start httpd
        run: |
          sudo systemctl enable httpd && systemctl restart httpd


